spring.application.name=RoomEase
spring.datasource.url=jdbc:mysql://localhost:3306/pg_management_system
spring.datasource.username=root
spring.datasource.password=percy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.flyway.enabled=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587

spring.mail.username=4a6f32892df6bc
spring.mail.password=304239927d951c

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

debug=true

jwt.secret=MzJCeXRlU3VwZXJTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY3ODkwMTIzNDU2
jwt.expiration=86400000